// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:ripple/models/app_settings.dart';
import 'package:ripple/models/chat.dart';
import 'package:ripple/models/contact.dart';
import 'package:ripple/models/message.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(ChatAdapter());
    registerAdapter(ContactAdapter());
    registerAdapter(MessageAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(ChatAdapter());
    registerAdapter(ContactAdapter());
    registerAdapter(MessageAdapter());
  }
}
